// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe
{
    /// <summary>
    /// Builds and executes requests for operations under \ai\transcribe
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TranscribeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.OpenSubtitles.OpenApiClient.ai.transcribe.item collection</summary>
        /// <param name="position">correlation_id</param>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.Item.WithCorrelation_ItemRequestBuilder"/></returns>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.Item.WithCorrelation_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("correlation_id", position);
                return new global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.Item.WithCorrelation_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TranscribeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ai/transcribe?api={api}&file={file}&language={language}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TranscribeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ai/transcribe?api={api}&file={file}&language={language}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;**Transcribe** media (audio, video) file using AI into subtitles. Max size of file: 100 MB Credits on user account are needed. [Buy Credits](../open_api.json/paths/~1ai~1credits~1buy/get)Check following method: [Get AI Transcribe status](../open_api.json/paths/~1ai~1transcribe~1{correlation_id}/get)Method is returning ```{  \&quot;status\&quot;: \&quot;CREATED\&quot;,  \&quot;correlation_id\&quot;: \&quot;67eda18f52e11\&quot;}```Status possible values: ```CREATED     -&gt; Initial state`PENDING     -&gt; procedure is still runningCOMPLETED   -&gt; remote procedure call is completed and has a resultERROR       -&gt; procedure resulted in an error and is not running anymoreTIMEOUT     -&gt; No matching procedure call found before timeout```Using `correlation_id` can check status of job using GET&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribePostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribePostResponse?> PostAsync(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribeRequestBuilder.TranscribeRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribePostResponse> PostAsync(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribeRequestBuilder.TranscribeRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribePostResponse>(requestInfo, global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribePostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;**Transcribe** media (audio, video) file using AI into subtitles. Max size of file: 100 MB Credits on user account are needed. [Buy Credits](../open_api.json/paths/~1ai~1credits~1buy/get)Check following method: [Get AI Transcribe status](../open_api.json/paths/~1ai~1transcribe~1{correlation_id}/get)Method is returning ```{  \&quot;status\&quot;: \&quot;CREATED\&quot;,  \&quot;correlation_id\&quot;: \&quot;67eda18f52e11\&quot;}```Status possible values: ```CREATED     -&gt; Initial state`PENDING     -&gt; procedure is still runningCOMPLETED   -&gt; remote procedure call is completed and has a resultERROR       -&gt; procedure resulted in an error and is not running anymoreTIMEOUT     -&gt; No matching procedure call found before timeout```Using `correlation_id` can check status of job using GET&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribeRequestBuilder.TranscribeRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribeRequestBuilder.TranscribeRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "multipart/form-data;q=0.1");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribeRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;**Transcribe** media (audio, video) file using AI into subtitles. Max size of file: 100 MB Credits on user account are needed. [Buy Credits](../open_api.json/paths/~1ai~1credits~1buy/get)Check following method: [Get AI Transcribe status](../open_api.json/paths/~1ai~1transcribe~1{correlation_id}/get)Method is returning ```{  \&quot;status\&quot;: \&quot;CREATED\&quot;,  \&quot;correlation_id\&quot;: \&quot;67eda18f52e11\&quot;}```Status possible values: ```CREATED     -&gt; Initial state`PENDING     -&gt; procedure is still runningCOMPLETED   -&gt; remote procedure call is completed and has a resultERROR       -&gt; procedure resulted in an error and is not running anymoreTIMEOUT     -&gt; No matching procedure call found before timeout```Using `correlation_id` can check status of job using GET&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TranscribeRequestBuilderPostQueryParameters 
        {
            /// <summary>transcribe API</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api")]
            public string? Api { get; set; }
#nullable restore
#else
            [QueryParameter("api")]
            public string Api { get; set; }
#endif
            /// <summary>media file</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("file")]
            public string? File { get; set; }
#nullable restore
#else
            [QueryParameter("file")]
            public string File { get; set; }
#endif
            /// <summary>language of media file</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("language")]
            public string? Language { get; set; }
#nullable restore
#else
            [QueryParameter("language")]
            public string Language { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
