// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenSubtitles.OpenApiClient.Utilities.Guessit;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Utilities
{
    /// <summary>
    /// Builds and executes requests for operations under \utilities
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UtilitiesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The guessit property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Utilities.Guessit.GuessitRequestBuilder Guessit
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Utilities.Guessit.GuessitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Utilities.UtilitiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UtilitiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/utilities", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Utilities.UtilitiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UtilitiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/utilities", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
