// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.OpenSubtitles.OpenApiClient.Ai;
using Soenneker.OpenSubtitles.OpenApiClient.Discover;
using Soenneker.OpenSubtitles.OpenApiClient.Download;
using Soenneker.OpenSubtitles.OpenApiClient.Features;
using Soenneker.OpenSubtitles.OpenApiClient.Infos;
using Soenneker.OpenSubtitles.OpenApiClient.Login;
using Soenneker.OpenSubtitles.OpenApiClient.Logout;
using Soenneker.OpenSubtitles.OpenApiClient.Subtitles;
using Soenneker.OpenSubtitles.OpenApiClient.Utilities;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OpenSubtitlesOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The ai property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Ai.AiRequestBuilder Ai
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Ai.AiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The discover property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Discover.DiscoverRequestBuilder Discover
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Discover.DiscoverRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The download property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Download.DownloadRequestBuilder Download
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Download.DownloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The features property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Features.FeaturesRequestBuilder Features
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Features.FeaturesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The infos property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Infos.InfosRequestBuilder Infos
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Infos.InfosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Login.LoginRequestBuilder Login
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logout property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Logout.LogoutRequestBuilder Logout
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subtitles property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Subtitles.SubtitlesRequestBuilder Subtitles
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Subtitles.SubtitlesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The utilities property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Utilities.UtilitiesRequestBuilder Utilities
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Utilities.UtilitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.OpenSubtitlesOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OpenSubtitlesOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.opensubtitles.com/api/v1";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
