// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenSubtitles.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_text
{
    /// <summary>
    /// Builds and executes requests for operations under \ai\detect_language_text
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Detect_language_textRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_text.Detect_language_textRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Detect_language_textRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ai/detect_language_text?file={file}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_text.Detect_language_textRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Detect_language_textRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ai/detect_language_text?file={file}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;**Detect language** of subtitle file.At least 1 credits on user account is needed. [Buy Credits](../open_api.json/paths/~1ai~1credits~1buy/get)Method is returning ```{  \&quot;data\&quot;: {    \&quot;format\&quot;: \&quot;SubRip\&quot;,    \&quot;type\&quot;: \&quot;text\&quot;,    \&quot;language\&quot;: {      \&quot;W3C\&quot;: \&quot;en\&quot;,      \&quot;name\&quot;: \&quot;english\&quot;,      \&quot;native\&quot;: \&quot;english\&quot;,      \&quot;ISO_639_1\&quot;: \&quot;en\&quot;,      \&quot;ISO_639_2b\&quot;: \&quot;eng\&quot;    }  }}```&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Detect_language_text_200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Detect_language_text_200?> PostAsync(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_text.Detect_language_textRequestBuilder.Detect_language_textRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Detect_language_text_200> PostAsync(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_text.Detect_language_textRequestBuilder.Detect_language_textRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Detect_language_text_200>(requestInfo, global::Soenneker.OpenSubtitles.OpenApiClient.Models.Detect_language_text_200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;**Detect language** of subtitle file.At least 1 credits on user account is needed. [Buy Credits](../open_api.json/paths/~1ai~1credits~1buy/get)Method is returning ```{  \&quot;data\&quot;: {    \&quot;format\&quot;: \&quot;SubRip\&quot;,    \&quot;type\&quot;: \&quot;text\&quot;,    \&quot;language\&quot;: {      \&quot;W3C\&quot;: \&quot;en\&quot;,      \&quot;name\&quot;: \&quot;english\&quot;,      \&quot;native\&quot;: \&quot;english\&quot;,      \&quot;ISO_639_1\&quot;: \&quot;en\&quot;,      \&quot;ISO_639_2b\&quot;: \&quot;eng\&quot;    }  }}```&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_text.Detect_language_textRequestBuilder.Detect_language_textRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_text.Detect_language_textRequestBuilder.Detect_language_textRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "multipart/form-data;q=0.1");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_text.Detect_language_textRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_text.Detect_language_textRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_text.Detect_language_textRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;**Detect language** of subtitle file.At least 1 credits on user account is needed. [Buy Credits](../open_api.json/paths/~1ai~1credits~1buy/get)Method is returning ```{  \&quot;data\&quot;: {    \&quot;format\&quot;: \&quot;SubRip\&quot;,    \&quot;type\&quot;: \&quot;text\&quot;,    \&quot;language\&quot;: {      \&quot;W3C\&quot;: \&quot;en\&quot;,      \&quot;name\&quot;: \&quot;english\&quot;,      \&quot;native\&quot;: \&quot;english\&quot;,      \&quot;ISO_639_1\&quot;: \&quot;en\&quot;,      \&quot;ISO_639_2b\&quot;: \&quot;eng\&quot;    }  }}```&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Detect_language_textRequestBuilderPostQueryParameters 
        {
            /// <summary>subtitle file</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("file")]
            public string? File { get; set; }
#nullable restore
#else
            [QueryParameter("file")]
            public string File { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
