// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Download : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>file_id from /subtitles search results</summary>
        public int? FileId { get; set; }
        /// <summary>desired file name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileName { get; set; }
#nullable restore
#else
        public string FileName { get; set; }
#endif
        /// <summary>(1/0) set subtitle file headers to &quot;application/force-download&quot;</summary>
        public bool? ForceDownload { get; set; }
        /// <summary>used for conversions, in_fps and out_fps must then be indicated</summary>
        public double? InFps { get; set; }
        /// <summary>used for conversions, in_fps and out_fps must then be indicated</summary>
        public double? OutFps { get; set; }
        /// <summary>from /infos/formats</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubFormat { get; set; }
#nullable restore
#else
        public string SubFormat { get; set; }
#endif
        /// <summary>delay to add or remove to the subtitle, + or - value, in seconds, i.e. 2.5s or -1s </summary>
        public double? Timeshift { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Download"/> and sets the default values.
        /// </summary>
        public Download()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Download"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenSubtitles.OpenApiClient.Models.Download CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenSubtitles.OpenApiClient.Models.Download();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "file_id", n => { FileId = n.GetIntValue(); } },
                { "file_name", n => { FileName = n.GetStringValue(); } },
                { "force_download", n => { ForceDownload = n.GetBoolValue(); } },
                { "in_fps", n => { InFps = n.GetDoubleValue(); } },
                { "out_fps", n => { OutFps = n.GetDoubleValue(); } },
                { "sub_format", n => { SubFormat = n.GetStringValue(); } },
                { "timeshift", n => { Timeshift = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("file_id", FileId);
            writer.WriteStringValue("file_name", FileName);
            writer.WriteBoolValue("force_download", ForceDownload);
            writer.WriteDoubleValue("in_fps", InFps);
            writer.WriteDoubleValue("out_fps", OutFps);
            writer.WriteStringValue("sub_format", SubFormat);
            writer.WriteDoubleValue("timeshift", Timeshift);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
