// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FeatureEpisodeAttributesSubtitlesCounts : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ar property</summary>
        public double? Ar { get; set; }
        /// <summary>The bg property</summary>
        public double? Bg { get; set; }
        /// <summary>The bs property</summary>
        public double? Bs { get; set; }
        /// <summary>The cs property</summary>
        public double? Cs { get; set; }
        /// <summary>The da property</summary>
        public double? Da { get; set; }
        /// <summary>The de property</summary>
        public double? De { get; set; }
        /// <summary>The el property</summary>
        public double? El { get; set; }
        /// <summary>The en property</summary>
        public double? En { get; set; }
        /// <summary>The es property</summary>
        public double? Es { get; set; }
        /// <summary>The et property</summary>
        public double? Et { get; set; }
        /// <summary>The fi property</summary>
        public double? Fi { get; set; }
        /// <summary>The fr property</summary>
        public double? Fr { get; set; }
        /// <summary>The he property</summary>
        public double? He { get; set; }
        /// <summary>The hr property</summary>
        public double? Hr { get; set; }
        /// <summary>The hu property</summary>
        public double? Hu { get; set; }
        /// <summary>The mk property</summary>
        public double? Mk { get; set; }
        /// <summary>The nl property</summary>
        public double? Nl { get; set; }
        /// <summary>The no property</summary>
        public double? No { get; set; }
        /// <summary>The pl property</summary>
        public double? Pl { get; set; }
        /// <summary>The ptBR property</summary>
        public double? PtBR { get; set; }
        /// <summary>The ptPT property</summary>
        public double? PtPT { get; set; }
        /// <summary>The ro property</summary>
        public double? Ro { get; set; }
        /// <summary>The ru property</summary>
        public double? Ru { get; set; }
        /// <summary>The sl property</summary>
        public double? Sl { get; set; }
        /// <summary>The sr property</summary>
        public double? Sr { get; set; }
        /// <summary>The sv property</summary>
        public double? Sv { get; set; }
        /// <summary>The th property</summary>
        public double? Th { get; set; }
        /// <summary>The tr property</summary>
        public double? Tr { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureEpisodeAttributesSubtitlesCounts"/> and sets the default values.
        /// </summary>
        public FeatureEpisodeAttributesSubtitlesCounts()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureEpisodeAttributesSubtitlesCounts"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureEpisodeAttributesSubtitlesCounts CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureEpisodeAttributesSubtitlesCounts();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ar", n => { Ar = n.GetDoubleValue(); } },
                { "bg", n => { Bg = n.GetDoubleValue(); } },
                { "bs", n => { Bs = n.GetDoubleValue(); } },
                { "cs", n => { Cs = n.GetDoubleValue(); } },
                { "da", n => { Da = n.GetDoubleValue(); } },
                { "de", n => { De = n.GetDoubleValue(); } },
                { "el", n => { El = n.GetDoubleValue(); } },
                { "en", n => { En = n.GetDoubleValue(); } },
                { "es", n => { Es = n.GetDoubleValue(); } },
                { "et", n => { Et = n.GetDoubleValue(); } },
                { "fi", n => { Fi = n.GetDoubleValue(); } },
                { "fr", n => { Fr = n.GetDoubleValue(); } },
                { "he", n => { He = n.GetDoubleValue(); } },
                { "hr", n => { Hr = n.GetDoubleValue(); } },
                { "hu", n => { Hu = n.GetDoubleValue(); } },
                { "mk", n => { Mk = n.GetDoubleValue(); } },
                { "nl", n => { Nl = n.GetDoubleValue(); } },
                { "no", n => { No = n.GetDoubleValue(); } },
                { "pl", n => { Pl = n.GetDoubleValue(); } },
                { "pt-BR", n => { PtBR = n.GetDoubleValue(); } },
                { "pt-PT", n => { PtPT = n.GetDoubleValue(); } },
                { "ro", n => { Ro = n.GetDoubleValue(); } },
                { "ru", n => { Ru = n.GetDoubleValue(); } },
                { "sl", n => { Sl = n.GetDoubleValue(); } },
                { "sr", n => { Sr = n.GetDoubleValue(); } },
                { "sv", n => { Sv = n.GetDoubleValue(); } },
                { "th", n => { Th = n.GetDoubleValue(); } },
                { "tr", n => { Tr = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("ar", Ar);
            writer.WriteDoubleValue("bg", Bg);
            writer.WriteDoubleValue("bs", Bs);
            writer.WriteDoubleValue("cs", Cs);
            writer.WriteDoubleValue("da", Da);
            writer.WriteDoubleValue("de", De);
            writer.WriteDoubleValue("el", El);
            writer.WriteDoubleValue("en", En);
            writer.WriteDoubleValue("es", Es);
            writer.WriteDoubleValue("et", Et);
            writer.WriteDoubleValue("fi", Fi);
            writer.WriteDoubleValue("fr", Fr);
            writer.WriteDoubleValue("he", He);
            writer.WriteDoubleValue("hr", Hr);
            writer.WriteDoubleValue("hu", Hu);
            writer.WriteDoubleValue("mk", Mk);
            writer.WriteDoubleValue("nl", Nl);
            writer.WriteDoubleValue("no", No);
            writer.WriteDoubleValue("pl", Pl);
            writer.WriteDoubleValue("pt-BR", PtBR);
            writer.WriteDoubleValue("pt-PT", PtPT);
            writer.WriteDoubleValue("ro", Ro);
            writer.WriteDoubleValue("ru", Ru);
            writer.WriteDoubleValue("sl", Sl);
            writer.WriteDoubleValue("sr", Sr);
            writer.WriteDoubleValue("sv", Sv);
            writer.WriteDoubleValue("th", Th);
            writer.WriteDoubleValue("tr", Tr);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
