// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Feature_Movie_attributes : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The episode_number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_episode_number? EpisodeNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_episode_number EpisodeNumber { get; set; }
#endif
        /// <summary>The feature_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FeatureId { get; set; }
#nullable restore
#else
        public string FeatureId { get; set; }
#endif
        /// <summary>The feature_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FeatureType { get; set; }
#nullable restore
#else
        public string FeatureType { get; set; }
#endif
        /// <summary>The imdb_id property</summary>
        public double? ImdbId { get; set; }
        /// <summary>The img_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImgUrl { get; set; }
#nullable restore
#else
        public string ImgUrl { get; set; }
#endif
        /// <summary>The original_title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalTitle { get; set; }
#nullable restore
#else
        public string OriginalTitle { get; set; }
#endif
        /// <summary>The parent_imdb_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_parent_imdb_id? ParentImdbId { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_parent_imdb_id ParentImdbId { get; set; }
#endif
        /// <summary>The parent_title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentTitle { get; set; }
#nullable restore
#else
        public string ParentTitle { get; set; }
#endif
        /// <summary>The season_number property</summary>
        public double? SeasonNumber { get; set; }
        /// <summary>The seasons_count property</summary>
        public double? SeasonsCount { get; set; }
        /// <summary>The subtitles_count property</summary>
        public double? SubtitlesCount { get; set; }
        /// <summary>The subtitles_counts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_subtitles_counts? SubtitlesCounts { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_subtitles_counts SubtitlesCounts { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The title_aka property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_title_aka>? TitleAka { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_title_aka> TitleAka { get; set; }
#endif
        /// <summary>The tmdb_id property</summary>
        public double? TmdbId { get; set; }
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The year property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Year { get; set; }
#nullable restore
#else
        public string Year { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes"/> and sets the default values.
        /// </summary>
        public Feature_Movie_attributes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "episode_number", n => { EpisodeNumber = n.GetObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_episode_number>(global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_episode_number.CreateFromDiscriminatorValue); } },
                { "feature_id", n => { FeatureId = n.GetStringValue(); } },
                { "feature_type", n => { FeatureType = n.GetStringValue(); } },
                { "imdb_id", n => { ImdbId = n.GetDoubleValue(); } },
                { "img_url", n => { ImgUrl = n.GetStringValue(); } },
                { "original_title", n => { OriginalTitle = n.GetStringValue(); } },
                { "parent_imdb_id", n => { ParentImdbId = n.GetObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_parent_imdb_id>(global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_parent_imdb_id.CreateFromDiscriminatorValue); } },
                { "parent_title", n => { ParentTitle = n.GetStringValue(); } },
                { "season_number", n => { SeasonNumber = n.GetDoubleValue(); } },
                { "seasons_count", n => { SeasonsCount = n.GetDoubleValue(); } },
                { "subtitles_count", n => { SubtitlesCount = n.GetDoubleValue(); } },
                { "subtitles_counts", n => { SubtitlesCounts = n.GetObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_subtitles_counts>(global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_subtitles_counts.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "title_aka", n => { TitleAka = n.GetCollectionOfObjectValues<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_title_aka>(global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_title_aka.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tmdb_id", n => { TmdbId = n.GetDoubleValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "year", n => { Year = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_episode_number>("episode_number", EpisodeNumber);
            writer.WriteStringValue("feature_id", FeatureId);
            writer.WriteStringValue("feature_type", FeatureType);
            writer.WriteDoubleValue("imdb_id", ImdbId);
            writer.WriteStringValue("img_url", ImgUrl);
            writer.WriteStringValue("original_title", OriginalTitle);
            writer.WriteObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_parent_imdb_id>("parent_imdb_id", ParentImdbId);
            writer.WriteStringValue("parent_title", ParentTitle);
            writer.WriteDoubleValue("season_number", SeasonNumber);
            writer.WriteDoubleValue("seasons_count", SeasonsCount);
            writer.WriteDoubleValue("subtitles_count", SubtitlesCount);
            writer.WriteObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_subtitles_counts>("subtitles_counts", SubtitlesCounts);
            writer.WriteStringValue("title", Title);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Feature_Movie_attributes_title_aka>("title_aka", TitleAka);
            writer.WriteDoubleValue("tmdb_id", TmdbId);
            writer.WriteStringValue("url", Url);
            writer.WriteStringValue("year", Year);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
