// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Features200 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The episode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureEpisode? Episode { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureEpisode Episode { get; set; }
#endif
        /// <summary>The movie property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureMovie? Movie { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureMovie Movie { get; set; }
#endif
        /// <summary>The tv property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureTvshow? Tv { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureTvshow Tv { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Features200"/> and sets the default values.
        /// </summary>
        public Features200()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Features200"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenSubtitles.OpenApiClient.Models.Features200 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenSubtitles.OpenApiClient.Models.Features200();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "episode", n => { Episode = n.GetObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureEpisode>(global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureEpisode.CreateFromDiscriminatorValue); } },
                { "movie", n => { Movie = n.GetObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureMovie>(global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureMovie.CreateFromDiscriminatorValue); } },
                { "tv", n => { Tv = n.GetObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureTvshow>(global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureTvshow.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureEpisode>("episode", Episode);
            writer.WriteObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureMovie>("movie", Movie);
            writer.WriteObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.FeatureTvshow>("tv", Tv);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
