// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Login_200 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The base_url property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200_base_url? BaseUrl { get; set; }
        /// <summary>The status property</summary>
        public double? Status { get; set; }
        /// <summary>The token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200_user? User { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200_user User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200"/> and sets the default values.
        /// </summary>
        public Login_200()
        {
            AdditionalData = new Dictionary<string, object>();
            BaseUrl = global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200_base_url.ApiOpensubtitlesCom;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "base_url", n => { BaseUrl = n.GetEnumValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200_base_url>(); } },
                { "status", n => { Status = n.GetDoubleValue(); } },
                { "token", n => { Token = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200_user>(global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200_user.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200_base_url>("base_url", BaseUrl);
            writer.WriteDoubleValue("status", Status);
            writer.WriteStringValue("token", Token);
            writer.WriteObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200_user>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
