// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Login200_base_url
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "api.opensubtitles.com")]
        #pragma warning disable CS1591
        ApiOpensubtitlesCom,
        #pragma warning restore CS1591
        [EnumMember(Value = "vip-api.opensubtitles.com")]
        #pragma warning disable CS1591
        VipApiOpensubtitlesCom,
        #pragma warning restore CS1591
    }
}
