// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Login_200_user : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allowed_downloads property</summary>
        public double? AllowedDownloads { get; set; }
        /// <summary>The allowed_translations property</summary>
        public double? AllowedTranslations { get; set; }
        /// <summary>The ext_installed property</summary>
        public bool? ExtInstalled { get; set; }
        /// <summary>The level property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level { get; set; }
#nullable restore
#else
        public string Level { get; set; }
#endif
        /// <summary>The user_id property</summary>
        public double? UserId { get; set; }
        /// <summary>The vip property</summary>
        public bool? Vip { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200_user"/> and sets the default values.
        /// </summary>
        public Login_200_user()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200_user"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200_user CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenSubtitles.OpenApiClient.Models.Login_200_user();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowed_downloads", n => { AllowedDownloads = n.GetDoubleValue(); } },
                { "allowed_translations", n => { AllowedTranslations = n.GetDoubleValue(); } },
                { "ext_installed", n => { ExtInstalled = n.GetBoolValue(); } },
                { "level", n => { Level = n.GetStringValue(); } },
                { "user_id", n => { UserId = n.GetDoubleValue(); } },
                { "vip", n => { Vip = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("allowed_downloads", AllowedDownloads);
            writer.WriteDoubleValue("allowed_translations", AllowedTranslations);
            writer.WriteBoolValue("ext_installed", ExtInstalled);
            writer.WriteStringValue("level", Level);
            writer.WriteDoubleValue("user_id", UserId);
            writer.WriteBoolValue("vip", Vip);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
