// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Subtitle_attributes_feature_details : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The feature_id property</summary>
        public double? FeatureId { get; set; }
        /// <summary>The feature_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FeatureType { get; set; }
#nullable restore
#else
        public string FeatureType { get; set; }
#endif
        /// <summary>The imdb_id property</summary>
        public double? ImdbId { get; set; }
        /// <summary>The movie_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MovieName { get; set; }
#nullable restore
#else
        public string MovieName { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The tmdb_id property</summary>
        public double? TmdbId { get; set; }
        /// <summary>The year property</summary>
        public double? Year { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_feature_details"/> and sets the default values.
        /// </summary>
        public Subtitle_attributes_feature_details()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_feature_details"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_feature_details CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_feature_details();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "feature_id", n => { FeatureId = n.GetDoubleValue(); } },
                { "feature_type", n => { FeatureType = n.GetStringValue(); } },
                { "imdb_id", n => { ImdbId = n.GetDoubleValue(); } },
                { "movie_name", n => { MovieName = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "tmdb_id", n => { TmdbId = n.GetDoubleValue(); } },
                { "year", n => { Year = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("feature_id", FeatureId);
            writer.WriteStringValue("feature_type", FeatureType);
            writer.WriteDoubleValue("imdb_id", ImdbId);
            writer.WriteStringValue("movie_name", MovieName);
            writer.WriteStringValue("title", Title);
            writer.WriteDoubleValue("tmdb_id", TmdbId);
            writer.WriteDoubleValue("year", Year);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
