// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Subtitle_attributes : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ai_translated property</summary>
        public bool? AiTranslated { get; set; }
        /// <summary>The comments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comments { get; set; }
#nullable restore
#else
        public string Comments { get; set; }
#endif
        /// <summary>The download_count property</summary>
        public double? DownloadCount { get; set; }
        /// <summary>The feature_details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_feature_details? FeatureDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_feature_details FeatureDetails { get; set; }
#endif
        /// <summary>The files property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_files>? Files { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_files> Files { get; set; }
#endif
        /// <summary>The foreign_parts_only property</summary>
        public bool? ForeignPartsOnly { get; set; }
        /// <summary>The fps property</summary>
        public double? Fps { get; set; }
        /// <summary>The from_trusted property</summary>
        public bool? FromTrusted { get; set; }
        /// <summary>The hd property</summary>
        public bool? Hd { get; set; }
        /// <summary>The hearing_impaired property</summary>
        public bool? HearingImpaired { get; set; }
        /// <summary>The language property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>The legacy_subtitle_id property</summary>
        public double? LegacySubtitleId { get; set; }
        /// <summary>The machine_translated property</summary>
        public bool? MachineTranslated { get; set; }
        /// <summary>The new_download_count property</summary>
        public double? NewDownloadCount { get; set; }
        /// <summary>The points property</summary>
        public double? Points { get; set; }
        /// <summary>The ratings property</summary>
        public double? Ratings { get; set; }
        /// <summary>The related_links property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_related_links>? RelatedLinks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_related_links> RelatedLinks { get; set; }
#endif
        /// <summary>The release property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Release { get; set; }
#nullable restore
#else
        public string Release { get; set; }
#endif
        /// <summary>The subtitle_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubtitleId { get; set; }
#nullable restore
#else
        public string SubtitleId { get; set; }
#endif
        /// <summary>The upload_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UploadDate { get; set; }
#nullable restore
#else
        public string UploadDate { get; set; }
#endif
        /// <summary>The uploader property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_uploader? Uploader { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_uploader Uploader { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The votes property</summary>
        public double? Votes { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes"/> and sets the default values.
        /// </summary>
        public Subtitle_attributes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ai_translated", n => { AiTranslated = n.GetBoolValue(); } },
                { "comments", n => { Comments = n.GetStringValue(); } },
                { "download_count", n => { DownloadCount = n.GetDoubleValue(); } },
                { "feature_details", n => { FeatureDetails = n.GetObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_feature_details>(global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_feature_details.CreateFromDiscriminatorValue); } },
                { "files", n => { Files = n.GetCollectionOfObjectValues<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_files>(global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_files.CreateFromDiscriminatorValue)?.AsList(); } },
                { "foreign_parts_only", n => { ForeignPartsOnly = n.GetBoolValue(); } },
                { "fps", n => { Fps = n.GetDoubleValue(); } },
                { "from_trusted", n => { FromTrusted = n.GetBoolValue(); } },
                { "hd", n => { Hd = n.GetBoolValue(); } },
                { "hearing_impaired", n => { HearingImpaired = n.GetBoolValue(); } },
                { "language", n => { Language = n.GetStringValue(); } },
                { "legacy_subtitle_id", n => { LegacySubtitleId = n.GetDoubleValue(); } },
                { "machine_translated", n => { MachineTranslated = n.GetBoolValue(); } },
                { "new_download_count", n => { NewDownloadCount = n.GetDoubleValue(); } },
                { "points", n => { Points = n.GetDoubleValue(); } },
                { "ratings", n => { Ratings = n.GetDoubleValue(); } },
                { "related_links", n => { RelatedLinks = n.GetCollectionOfObjectValues<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_related_links>(global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_related_links.CreateFromDiscriminatorValue)?.AsList(); } },
                { "release", n => { Release = n.GetStringValue(); } },
                { "subtitle_id", n => { SubtitleId = n.GetStringValue(); } },
                { "upload_date", n => { UploadDate = n.GetStringValue(); } },
                { "uploader", n => { Uploader = n.GetObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_uploader>(global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_uploader.CreateFromDiscriminatorValue); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "votes", n => { Votes = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("ai_translated", AiTranslated);
            writer.WriteStringValue("comments", Comments);
            writer.WriteDoubleValue("download_count", DownloadCount);
            writer.WriteObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_feature_details>("feature_details", FeatureDetails);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_files>("files", Files);
            writer.WriteBoolValue("foreign_parts_only", ForeignPartsOnly);
            writer.WriteDoubleValue("fps", Fps);
            writer.WriteBoolValue("from_trusted", FromTrusted);
            writer.WriteBoolValue("hd", Hd);
            writer.WriteBoolValue("hearing_impaired", HearingImpaired);
            writer.WriteStringValue("language", Language);
            writer.WriteDoubleValue("legacy_subtitle_id", LegacySubtitleId);
            writer.WriteBoolValue("machine_translated", MachineTranslated);
            writer.WriteDoubleValue("new_download_count", NewDownloadCount);
            writer.WriteDoubleValue("points", Points);
            writer.WriteDoubleValue("ratings", Ratings);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_related_links>("related_links", RelatedLinks);
            writer.WriteStringValue("release", Release);
            writer.WriteStringValue("subtitle_id", SubtitleId);
            writer.WriteStringValue("upload_date", UploadDate);
            writer.WriteObjectValue<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitle_attributes_uploader>("uploader", Uploader);
            writer.WriteStringValue("url", Url);
            writer.WriteDoubleValue("votes", Votes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
