// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Subtitles200_data_attributes_feature_details : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The episode_number property</summary>
        public int? EpisodeNumber { get; set; }
        /// <summary>The feature_id property</summary>
        public int? FeatureId { get; set; }
        /// <summary>The feature_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FeatureType { get; set; }
#nullable restore
#else
        public string FeatureType { get; set; }
#endif
        /// <summary>The imdb_id property</summary>
        public int? ImdbId { get; set; }
        /// <summary>The movie_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MovieName { get; set; }
#nullable restore
#else
        public string MovieName { get; set; }
#endif
        /// <summary>The parent_feature_id property</summary>
        public int? ParentFeatureId { get; set; }
        /// <summary>The parent_imdb_id property</summary>
        public int? ParentImdbId { get; set; }
        /// <summary>The parent_title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentTitle { get; set; }
#nullable restore
#else
        public string ParentTitle { get; set; }
#endif
        /// <summary>The parent_tmdb_id property</summary>
        public int? ParentTmdbId { get; set; }
        /// <summary>The season_number property</summary>
        public int? SeasonNumber { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The tmdb_id property</summary>
        public int? TmdbId { get; set; }
        /// <summary>The year property</summary>
        public int? Year { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitles200_data_attributes_feature_details"/> and sets the default values.
        /// </summary>
        public Subtitles200_data_attributes_feature_details()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitles200_data_attributes_feature_details"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitles200_data_attributes_feature_details CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenSubtitles.OpenApiClient.Models.Subtitles200_data_attributes_feature_details();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "episode_number", n => { EpisodeNumber = n.GetIntValue(); } },
                { "feature_id", n => { FeatureId = n.GetIntValue(); } },
                { "feature_type", n => { FeatureType = n.GetStringValue(); } },
                { "imdb_id", n => { ImdbId = n.GetIntValue(); } },
                { "movie_name", n => { MovieName = n.GetStringValue(); } },
                { "parent_feature_id", n => { ParentFeatureId = n.GetIntValue(); } },
                { "parent_imdb_id", n => { ParentImdbId = n.GetIntValue(); } },
                { "parent_title", n => { ParentTitle = n.GetStringValue(); } },
                { "parent_tmdb_id", n => { ParentTmdbId = n.GetIntValue(); } },
                { "season_number", n => { SeasonNumber = n.GetIntValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "tmdb_id", n => { TmdbId = n.GetIntValue(); } },
                { "year", n => { Year = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("episode_number", EpisodeNumber);
            writer.WriteIntValue("feature_id", FeatureId);
            writer.WriteStringValue("feature_type", FeatureType);
            writer.WriteIntValue("imdb_id", ImdbId);
            writer.WriteStringValue("movie_name", MovieName);
            writer.WriteIntValue("parent_feature_id", ParentFeatureId);
            writer.WriteIntValue("parent_imdb_id", ParentImdbId);
            writer.WriteStringValue("parent_title", ParentTitle);
            writer.WriteIntValue("parent_tmdb_id", ParentTmdbId);
            writer.WriteIntValue("season_number", SeasonNumber);
            writer.WriteStringValue("title", Title);
            writer.WriteIntValue("tmdb_id", TmdbId);
            writer.WriteIntValue("year", Year);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
