// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenSubtitles.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Features
{
    /// <summary>
    /// Builds and executes requests for operations under \features
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FeaturesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Features.FeaturesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FeaturesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/features{?feature_id*,full_search*,imdb_id*,query*,query_match*,tmdb_id*,type*,year*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Features.FeaturesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FeaturesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/features{?feature_id*,full_search*,imdb_id*,query*,query_match*,tmdb_id*,type*,year*}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;With the \&quot;query\&quot; parameter, search for a Feature from a simple text input. Typically used for a text search or autocomplete.With an ID, get basic information and subtitles count for a specific title.With the \&quot;query_match\&quot; you can define the matched applied to the query:  - \&quot;start\&quot; is the default behavior, it will query on the first letter entered to offer suggestions - \&quot;word\&quot; will return the match on the word, but not always matching the fulll title, for example searching \&quot;roma\&quot; will return \&quot;holiday in roma\&quot; - \&quot;exact\&quot; will exactly match the title, so here searching for \&quot;roma\&quot; will only return the movie(s) named \&quot;roma\&quot; With the \&quot;full_search\&quot; you can extend the search to the translations of the title, so \&quot;roma\&quot; will also return \&quot;rome\&quot; &lt;!-- theme: warning --&gt;&gt; ### Watch Out!&gt;&gt; If you create an autocomplete, don&apos;t set a too small refresh limit, remember you must not go over 40 requests per 10 seconds!&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Features_200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Features_200?> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Features.FeaturesRequestBuilder.FeaturesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Features_200> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Features.FeaturesRequestBuilder.FeaturesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Features_200>(requestInfo, global::Soenneker.OpenSubtitles.OpenApiClient.Models.Features_200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;With the \&quot;query\&quot; parameter, search for a Feature from a simple text input. Typically used for a text search or autocomplete.With an ID, get basic information and subtitles count for a specific title.With the \&quot;query_match\&quot; you can define the matched applied to the query:  - \&quot;start\&quot; is the default behavior, it will query on the first letter entered to offer suggestions - \&quot;word\&quot; will return the match on the word, but not always matching the fulll title, for example searching \&quot;roma\&quot; will return \&quot;holiday in roma\&quot; - \&quot;exact\&quot; will exactly match the title, so here searching for \&quot;roma\&quot; will only return the movie(s) named \&quot;roma\&quot; With the \&quot;full_search\&quot; you can extend the search to the translations of the title, so \&quot;roma\&quot; will also return \&quot;rome\&quot; &lt;!-- theme: warning --&gt;&gt; ### Watch Out!&gt;&gt; If you create an autocomplete, don&apos;t set a too small refresh limit, remember you must not go over 40 requests per 10 seconds!&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Features.FeaturesRequestBuilder.FeaturesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Features.FeaturesRequestBuilder.FeaturesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Features.FeaturesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Features.FeaturesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.OpenSubtitles.OpenApiClient.Features.FeaturesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;With the \&quot;query\&quot; parameter, search for a Feature from a simple text input. Typically used for a text search or autocomplete.With an ID, get basic information and subtitles count for a specific title.With the \&quot;query_match\&quot; you can define the matched applied to the query:  - \&quot;start\&quot; is the default behavior, it will query on the first letter entered to offer suggestions - \&quot;word\&quot; will return the match on the word, but not always matching the fulll title, for example searching \&quot;roma\&quot; will return \&quot;holiday in roma\&quot; - \&quot;exact\&quot; will exactly match the title, so here searching for \&quot;roma\&quot; will only return the movie(s) named \&quot;roma\&quot; With the \&quot;full_search\&quot; you can extend the search to the translations of the title, so \&quot;roma\&quot; will also return \&quot;rome\&quot; &lt;!-- theme: warning --&gt;&gt; ### Watch Out!&gt;&gt; If you create an autocomplete, don&apos;t set a too small refresh limit, remember you must not go over 40 requests per 10 seconds!&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FeaturesRequestBuilderGetQueryParameters 
        {
            /// <summary>opensubtitles **feature_id**</summary>
            [QueryParameter("feature_id")]
            public int? FeatureId { get; set; }
            /// <summary>Search on original title and title aka (translations) (default false)</summary>
            [QueryParameter("full_search")]
            public bool? FullSearch { get; set; }
            /// <summary>IMDB ID, delete leading zeroes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("imdb_id")]
            public string? ImdbId { get; set; }
#nullable restore
#else
            [QueryParameter("imdb_id")]
            public string ImdbId { get; set; }
#endif
            /// <summary>query to search, release/file name accepted</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            /// <summary>&quot;Type of matching applied to the query: **start** (default), **word**, **exact**  &quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query_match")]
            public string? QueryMatch { get; set; }
#nullable restore
#else
            [QueryParameter("query_match")]
            public string QueryMatch { get; set; }
#endif
            /// <summary>TheMovieDB ID - combine with type to avoid errors</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tmdb_id")]
            public string? TmdbId { get; set; }
#nullable restore
#else
            [QueryParameter("tmdb_id")]
            public string TmdbId { get; set; }
#endif
            /// <summary>empty to list all or **movie**, **tvshow** or **episode**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("type")]
            public string? Type { get; set; }
#nullable restore
#else
            [QueryParameter("type")]
            public string Type { get; set; }
#endif
            /// <summary>Filter by year. Can only be used in combination with a query</summary>
            [QueryParameter("year")]
            public int? Year { get; set; }
        }
    }
}
#pragma warning restore CS0618
