// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate
{
    /// <summary>
    /// Builds and executes requests for operations under \ai\translate
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TranslateRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.OpenSubtitles.OpenApiClient.ai.translate.item collection</summary>
        /// <param name="position">correlation_id</param>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.Item.WithCorrelation_ItemRequestBuilder"/></returns>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.Item.WithCorrelation_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("correlation_id", position);
                return new global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.Item.WithCorrelation_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TranslateRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ai/translate?api={api}&file={file}&translate_to={translate_to}{&file_id*,translate_from*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TranslateRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ai/translate?api={api}&file={file}&translate_to={translate_to}{&file_id*,translate_from*}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;**Translate** subtitles using AI from one language to another language. Credits on user account are needed. [Buy Credits](../open_api.json/paths/~1ai~1credits~1buy/get)Check following method: [Get AI Translate status](../open_api.json/paths/~1ai~1translate~1{correlation_id}/get)Method is returning ```{  \&quot;status\&quot;: \&quot;CREATED\&quot;,  \&quot;correlation_id\&quot;: \&quot;67eda18f52e11\&quot;}```Status possible values: ```CREATED     -&gt; Initial state`PENDING     -&gt; procedure is still runningCOMPLETED   -&gt; remote procedure call is completed and has a resultERROR       -&gt; procedure resulted in an error and is not running anymoreTIMEOUT     -&gt; No matching procedure call found before timeout```Using `correlation_id` can check status of job using GET&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslatePostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslatePostResponse?> PostAsync(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslateRequestBuilder.TranslateRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslatePostResponse> PostAsync(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslateRequestBuilder.TranslateRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslatePostResponse>(requestInfo, global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslatePostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;**Translate** subtitles using AI from one language to another language. Credits on user account are needed. [Buy Credits](../open_api.json/paths/~1ai~1credits~1buy/get)Check following method: [Get AI Translate status](../open_api.json/paths/~1ai~1translate~1{correlation_id}/get)Method is returning ```{  \&quot;status\&quot;: \&quot;CREATED\&quot;,  \&quot;correlation_id\&quot;: \&quot;67eda18f52e11\&quot;}```Status possible values: ```CREATED     -&gt; Initial state`PENDING     -&gt; procedure is still runningCOMPLETED   -&gt; remote procedure call is completed and has a resultERROR       -&gt; procedure resulted in an error and is not running anymoreTIMEOUT     -&gt; No matching procedure call found before timeout```Using `correlation_id` can check status of job using GET&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslateRequestBuilder.TranslateRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslateRequestBuilder.TranslateRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "multipart/form-data;q=0.1");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslateRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslateRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslateRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;**Translate** subtitles using AI from one language to another language. Credits on user account are needed. [Buy Credits](../open_api.json/paths/~1ai~1credits~1buy/get)Check following method: [Get AI Translate status](../open_api.json/paths/~1ai~1translate~1{correlation_id}/get)Method is returning ```{  \&quot;status\&quot;: \&quot;CREATED\&quot;,  \&quot;correlation_id\&quot;: \&quot;67eda18f52e11\&quot;}```Status possible values: ```CREATED     -&gt; Initial state`PENDING     -&gt; procedure is still runningCOMPLETED   -&gt; remote procedure call is completed and has a resultERROR       -&gt; procedure resulted in an error and is not running anymoreTIMEOUT     -&gt; No matching procedure call found before timeout```Using `correlation_id` can check status of job using GET&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TranslateRequestBuilderPostQueryParameters 
        {
            /// <summary>translation_apis</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api")]
            public string? Api { get; set; }
#nullable restore
#else
            [QueryParameter("api")]
            public string Api { get; set; }
#endif
            /// <summary>file contents to translate</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("file")]
            public string? File { get; set; }
#nullable restore
#else
            [QueryParameter("file")]
            public string File { get; set; }
#endif
            /// <summary>file_id from /subtitles endpoint</summary>
            [QueryParameter("file_id")]
            public int? FileId { get; set; }
            /// <summary>language ISO639 translate_from (auto is default)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("translate_from")]
            public string? TranslateFrom { get; set; }
#nullable restore
#else
            [QueryParameter("translate_from")]
            public string TranslateFrom { get; set; }
#endif
            /// <summary>language ISO639 translate_from</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("translate_to")]
            public string? TranslateTo { get; set; }
#nullable restore
#else
            [QueryParameter("translate_to")]
            public string TranslateTo { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
