// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenSubtitles.OpenApiClient.Discover.Latest;
using Soenneker.OpenSubtitles.OpenApiClient.Discover.Most_downloaded;
using Soenneker.OpenSubtitles.OpenApiClient.Discover.Popular;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Discover
{
    /// <summary>
    /// Builds and executes requests for operations under \discover
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DiscoverRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The latest property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Discover.Latest.LatestRequestBuilder Latest
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Discover.Latest.LatestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The most_downloaded property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Discover.Most_downloaded.Most_downloadedRequestBuilder Most_downloaded
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Discover.Most_downloaded.Most_downloadedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The popular property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Discover.Popular.PopularRequestBuilder Popular
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Discover.Popular.PopularRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Discover.DiscoverRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DiscoverRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/discover", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Discover.DiscoverRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DiscoverRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/discover", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
