// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenSubtitles.OpenApiClient.Ai.Info.Transcription;
using Soenneker.OpenSubtitles.OpenApiClient.Ai.Info.Translation;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Ai.Info
{
    /// <summary>
    /// Builds and executes requests for operations under \ai\info
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InfoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The transcription property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Info.Transcription.TranscriptionRequestBuilder Transcription
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Info.Transcription.TranscriptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The translation property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Info.Translation.TranslationRequestBuilder Translation
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Info.Translation.TranslationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Info.InfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InfoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ai/info", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Info.InfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InfoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ai/info", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
