// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenSubtitles.OpenApiClient.Infos.Formats;
using Soenneker.OpenSubtitles.OpenApiClient.Infos.Languages;
using Soenneker.OpenSubtitles.OpenApiClient.Infos.User;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Infos
{
    /// <summary>
    /// Builds and executes requests for operations under \infos
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InfosRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The formats property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Infos.Formats.FormatsRequestBuilder Formats
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Infos.Formats.FormatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The languages property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Infos.Languages.LanguagesRequestBuilder Languages
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Infos.Languages.LanguagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Infos.User.UserRequestBuilder User
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Infos.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Infos.InfosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InfosRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/infos", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Infos.InfosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InfosRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/infos", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
