// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenSubtitles.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Utilities.Guessit
{
    /// <summary>
    /// Builds and executes requests for operations under \utilities\guessit
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GuessitRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Utilities.Guessit.GuessitRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GuessitRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/utilities/guessit{?filename*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Utilities.Guessit.GuessitRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GuessitRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/utilities/guessit{?filename*}", rawUrl)
        {
        }
        /// <summary>
        /// Extracts as much information as possible from a video filename.It has a very powerful matcher that allows to guess properties from a video using its filename only. This matcher works with both movies and tv shows episodes.This is a simple implementation of the python guessit library.https://guessit-io.github.io/guessit/Find examples of the returned data.https://guessit-io.github.io/guessit/properties/
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Models.Guessit_200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Guessit_200?> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Utilities.Guessit.GuessitRequestBuilder.GuessitRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Guessit_200> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Utilities.Guessit.GuessitRequestBuilder.GuessitRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.OpenSubtitles.OpenApiClient.Models.Guessit_200>(requestInfo, global::Soenneker.OpenSubtitles.OpenApiClient.Models.Guessit_200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Extracts as much information as possible from a video filename.It has a very powerful matcher that allows to guess properties from a video using its filename only. This matcher works with both movies and tv shows episodes.This is a simple implementation of the python guessit library.https://guessit-io.github.io/guessit/Find examples of the returned data.https://guessit-io.github.io/guessit/properties/
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Utilities.Guessit.GuessitRequestBuilder.GuessitRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenSubtitles.OpenApiClient.Utilities.Guessit.GuessitRequestBuilder.GuessitRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Utilities.Guessit.GuessitRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Utilities.Guessit.GuessitRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.OpenSubtitles.OpenApiClient.Utilities.Guessit.GuessitRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Extracts as much information as possible from a video filename.It has a very powerful matcher that allows to guess properties from a video using its filename only. This matcher works with both movies and tv shows episodes.This is a simple implementation of the python guessit library.https://guessit-io.github.io/guessit/Find examples of the returned data.https://guessit-io.github.io/guessit/properties/
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GuessitRequestBuilderGetQueryParameters 
        {
            /// <summary>File name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filename")]
            public string? Filename { get; set; }
#nullable restore
#else
            [QueryParameter("filename")]
            public string Filename { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
