// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenSubtitles.OpenApiClient.Ai.Credits;
using Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_audio;
using Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_text;
using Soenneker.OpenSubtitles.OpenApiClient.Ai.Info;
using Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe;
using Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.OpenSubtitles.OpenApiClient.Ai
{
    /// <summary>
    /// Builds and executes requests for operations under \ai
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The credits property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Credits.CreditsRequestBuilder Credits
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Credits.CreditsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The detect_language_audio property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_audio.Detect_language_audioRequestBuilder Detect_language_audio
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_audio.Detect_language_audioRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The detect_language_text property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_text.Detect_language_textRequestBuilder Detect_language_text
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Detect_language_text.Detect_language_textRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The info property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Info.InfoRequestBuilder Info
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Info.InfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transcribe property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribeRequestBuilder Transcribe
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Transcribe.TranscribeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The translate property</summary>
        public global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslateRequestBuilder Translate
        {
            get => new global::Soenneker.OpenSubtitles.OpenApiClient.Ai.Translate.TranslateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.AiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ai", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenSubtitles.OpenApiClient.Ai.AiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ai", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
